#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=4
#SBATCH --mem=10G
#SBATCH --time=01:00:00

echo "stealing MNI reference NIFTI"
time singularity exec docker://brainlife/ants:2.2.0 cp /HCPpipelines/global/templates/MNI152_T1_1mm_brain.nii.gz .

#allow access to it
chmod 777 MNI152_T1_1mm_brain.nii.gz 

time singularity exec docker://brainlife/dipy:1.4.1 create_ROIs/createROIS.py

echo "warping coordinates from mni space"
time singularity exec docker://brainlife/ants:2.2.0 ROI_warp/CoordTransform.sh
